package com.lab.ocp.day14.playgame;

import javax.swing.ImageIcon;

public class FightJFrame extends javax.swing.JFrame {
    boolean isReady = true;
    private ImageIcon[] icon_ready = {
        new ImageIcon("src\\main\\java\\com\\lab\\ocp\\day14\\playgame\\images\\ready_0.png"),
        new ImageIcon("src\\main\\java\\com\\lab\\ocp\\day14\\playgame\\images\\ready_1.png"),
        new ImageIcon("src\\main\\java\\com\\lab\\ocp\\day14\\playgame\\images\\ready_2.png"),
        new ImageIcon("src\\main\\java\\com\\lab\\ocp\\day14\\playgame\\images\\ready_3.png"),
        new ImageIcon("src\\main\\java\\com\\lab\\ocp\\day14\\playgame\\images\\ready_4.png"),
        new ImageIcon("src\\main\\java\\com\\lab\\ocp\\day14\\playgame\\images\\ready_5.png"),
    };
    
    private ImageIcon[] icon_fight = {
        new ImageIcon("src\\main\\java\\com\\lab\\ocp\\day14\\playgame\\images\\fight_0.png"),
        new ImageIcon("src\\main\\java\\com\\lab\\ocp\\day14\\playgame\\images\\fight_1.png"),
        new ImageIcon("src\\main\\java\\com\\lab\\ocp\\day14\\playgame\\images\\fight_2.png"),
        new ImageIcon("src\\main\\java\\com\\lab\\ocp\\day14\\playgame\\images\\fight_3.png"),
        new ImageIcon("src\\main\\java\\com\\lab\\ocp\\day14\\playgame\\images\\fight_4.png"),
        new ImageIcon("src\\main\\java\\com\\lab\\ocp\\day14\\playgame\\images\\fight_5.png"),
    };
    
    class Ready extends Thread {
        @Override
        public void run() {
            for(int i=0;;i++) {
                i = i % icon_ready.length;
                if(isReady) 
                    actor.setIcon(icon_ready[i]);
                else
                    actor.setIcon(icon_fight[i]);
                try {
                    Thread.sleep(150);
                } catch (Exception e) {
                }
            }
        }
    }
    
    public FightJFrame() {
        initComponents();
        actor.setIcon(icon_ready[0]);
        new Ready().start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        actor.setText("小明");
        actor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                actorMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(actor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(actor, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actorMousePressed
        isReady = !isReady;
    }//GEN-LAST:event_actorMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FightJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FightJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FightJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FightJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FightJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actor;
    // End of variables declaration//GEN-END:variables
}
