package com.lab.ocp.day14.playgame;

import javax.swing.ImageIcon;

public class WalkJFrame extends javax.swing.JFrame {

    private static String path = "src\\main\\java\\com\\lab\\ocp\\day14\\playgame\\images\\";
    private static ImageIcon[] icons = {
        new ImageIcon(path + "hah_0.png"),
        new ImageIcon(path + "hah_1.png")
    };
    private static ImageIcon[] icons2 = {
        new ImageIcon(path + "walk_0.png"),
        new ImageIcon(path + "walk_1.png"),
        new ImageIcon(path + "walk_2.png"),
        new ImageIcon(path + "walk_3.png"),
        new ImageIcon(path + "walk_4.png"),
        new ImageIcon(path + "walk_5.png"),
    };
    
    Ready ready;
    public WalkJFrame() {
        initComponents();
        ready = new Ready();
        ready.start();
    }
    
    class Ready extends Thread {
        boolean isReady = true;
        int x, y;
        public Ready() {
            actor.setIcon(icons[0]);
            x = actor.getX();
            y = actor.getY();
        }
        
        @Override
        public void run() {
            for (int i=0;true;i++) {
                if(isReady)
                    actor.setIcon(icons[i % icons.length]);
                else {
                    actor.setIcon(icons2[i % icons2.length]);
                    x += 5;
                }
                actor.setLocation(x, y);
                try {
                    Thread.sleep(100);
                } catch (Exception e) {
                }
                if(i == Integer.MAX_VALUE) i = 0;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        actor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                actorMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(actor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(actor, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actorMousePressed
        ready.isReady = !ready.isReady;
    }//GEN-LAST:event_actorMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WalkJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WalkJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WalkJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WalkJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WalkJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actor;
    // End of variables declaration//GEN-END:variables
}
